### ISSUE TITLE
adapt commands to the new volumes

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni-tools#106]
follow up of https://github.com/uyuni-project/uyuni/pull/7651
Volumes required to be mount are changed, we need to adapt uyuni-tools to them

**Comment by mbussolotto** [comment]
`find /srv -type f -print0  | xargs -0  rpm -qf | grep -v "is not owned" `
- cobbler (as expected)
- pxe-default-image-opensuse15-4.4.0 (as expected)
- susemanager-sls for /srv/formula_metadata/README.md

**Comment by cbosdo** [comment]
That was done already.
