### ISSUE TITLE
Wrong version number with `mgr* --version`

### ISSUE THREAD

**Issue by nodeg** [uyuni-project/uyuni-tools#176]
## Description

Wile testing 5.0 Beta 1, we found out, that all 3 tools (`mgradm`, `mgrctl`, `mgrpxy`) shows a wrong version number when executing `mgr* --version`:

```bash
ominik-min:~ # mgradm --version
mgradm version 0.0.0
dominik-min:~ # mgradm -v
mgradm version 0.0.0
dominik-min:~ # rpm -q mgradm
mgradm-0.1.4-150500.1.1.x86_64

ominik-min:~ # mgrctl --version
mgrctl version 0.0.0
dominik-min:~ # mgrctl -v
mgrctl version 0.0.0
ominik-min:~ # rpm -q mgrctl
mgrctl-0.1.4-150500.1.1.x86_64

ominik-min2:~ # mgrpxy --version
mgrpxy version 0.0.0
dominik-min2:~ # mgrpxy -v
mgrpxy version 0.0.0
ominik-min2:~ # rpm -q mgrpxy
mgrpxy-0.1.4-150500.1.1.x86_64
```

**Comment by mbussolotto** [comment]
apparently we have problem in this mechanism:

https://github.com/uyuni-project/uyuni-tools/blob/57fce89cdb285a4c794478e4cff8e416f3f2cd0d/shared/utils/cmd.go#L21-L22

https://github.com/uyuni-project/uyuni-tools/blob/57fce89cdb285a4c794478e4cff8e416f3f2cd0d/build.sh#L13-L15

**Comment by mbussolotto** [comment]
this is the value shown after compiling and run `--version` locally:
```
mbussolotto@mbuthinkpad:~/Workspace/uyuni-tools (set_cobbler_localhost=)$ ./build.sh 
DONE
mbussolotto@mbuthinkpad:~/Workspace/uyuni-tools (set_cobbler_localhost=)$ bin/mgradm --version
mgradm version Manager-5.0-Beta1-51
```

I don't think that `Manager-5.0-Beta1-51` is the correct value as well, maybe OBS cannot fetch corectly `tag` and `offset` ?

**Comment by mbussolotto** [comment]
Actually spec file used this:
https://github.com/uyuni-project/uyuni-tools/blob/57fce89cdb285a4c794478e4cff8e416f3f2cd0d/uyuni-tools.spec#L270-L273
