### ISSUE TITLE
Develop a prepare migration command

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#181]
For large deployments, especially with a huge number of packages and big database, migration can be complex and take a long time.

We should consider if we should have a prepare migration command which would rsync some folder that we know that are big, like:
- packages
- cache
- database

Since it's using rsync, it can be called several time without any problem, and with the source server running.

When the migration happens, we would stop the services on the source server, and run the migration command, which would rsync everything again and make the needed transformations.

**Comment by cbosdo** [comment]
I would suggest to add `--prepare` flag to the `mgradm migrate [podman|kubernetes]` commands that only runs the `rsync` parts of the migration script.

**Comment by admd** [comment]
As a user, when I run this command, I expect it to execute in the background with clear informational messages indicating that it will not perform the actual migration but will move some easily transferable data to save time during the actual migration. It would be ideal if users could check the status of this process though.

**Comment by cbosdo** [comment]
> As a user, when I run this command, I expect it to execute in the background with clear informational messages indicating that it will not perform the actual migration but will move some easily transferable data to save time during the actual migration. It would be ideal if users could check the status of this process though.

Why in the background? The user can always run this in a `screen` if needed.

**Comment by admd** [comment]
Ok yes, it should be fine to not run in background.

But then my question becomes, do we show what's happening behind the scene when running this command? We need to show some information or progress or anything. We cannot just run a command and then it just stuck there with no feedback to the user if something is happening or not. If we cover that part, we are good.

**Comment by nadvornik** [comment]
The user can see the output of rsync command - a list of synced files.

**Comment by cbosdo** [comment]
> The user can see the output of rsync command - a list of synced files.

Shouldn't we add `-P` to `rsync` to show the progress? or is what we have now good enough?
