### ISSUE TITLE
Integration with to cloud update infrastructure

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#205]
On cloud, users can decide to use the existing suse cloud update infrastructure to download the images. Currently in `mgradm` users are allowed to specify the image location and also the registry authentication username and password.

On mgradm we currently try to handle the registry authentication with the following option: Loads credentials created by SUSEConnect existing at `/etc/zypp/credentials.d/SCCcredentials` and call podman login

We would need to add another option, to connect to suse cloud update infrastructure. It would need to call a new tool under development by cloud team which will deal with all the authentication parts. After calling that tool we would be able to call podman pull directly.

To cloud infra, user would need to define the right image name (and registry) to pull the image from.

**Comment by cbosdo** [comment]
More precise tasks created on the go
