### ISSUE TITLE
`mgradm install` accepts wrong admin email address

### ISSUE THREAD

**Issue by nodeg** [uyuni-project/uyuni-tools#221]
# Description

When doing an installation with e.g. podman (`mgradm install podman`), the provided administrator email address is not properly checked.

Example:
```bash
localhost:~ # mgradm install podman
2:42PM INF Welcome to mgradm
2:42PM INF Executing command: podman
Password for the CA certificate to generate:
Administrator password:
Administrator's email: et
Not a valid email address

A value is required
Administrator's email: dgedon@aetaset

2:42PM INF setting up server with the FQDN 'localhost.localdomain'
2:42PM INF Ensure image registry.suse.de/devel/galaxy/manager/head/containerfile/suse/manager/5.0/x86_64/server:5.0.0-beta1 is available
2:42PM INF Setting up uyuni network
(...)

ocalhost:~ # mgradm -v
mgradm version 0.1.5
```

A solution would be e.g. to use https://github.com/AfterShip/email-verifier.

**Comment by aaannz** [comment]
This is interesting as we are using [net/mail](https://pkg.go.dev/net/mail#ParseAddress) build-in for mail validation.

**Comment by aaannz** [comment]
So according to quick wiki search, dot-less domain part is valid per the RFC5322
> admin@example (local domain name with no [TLD](https://en.wikipedia.org/wiki/Top-level_domain), although ICANN highly discourages dotless email addresses[[29]](https://en.wikipedia.org/wiki/Email_address#cite_note-29)

**Comment by cbosdo** [comment]
It's impossible the validate an email address. Let's close this for now and reopen later if it hurts too badly
