### ISSUE TITLE
`mgradm.yaml`: Provide template with all available options

### ISSUE THREAD

**Issue by nodeg** [uyuni-project/uyuni-tools#232]
# Description

Currently, there is no `mgradm.yaml` template with all the possible options one can use there. The only way to get them is by looking at

https://github.com/uyuni-project/uyuni-tools/blob/fe5677afb0205c2ea4c7ca1fcd125f1b7de26809/mgradm/cmd/install/shared/flags.go#L107-L167

# Proposal

Add a template file with all the available options that can be defined in the `mgradm.yaml` file.

**Comment by cbosdo** [comment]
Since all options are specific to each command, I don't think we can provide a template. Better read `mgradm config` in conjunction with the command's help.
