### ISSUE TITLE
Add `mgrctl connect` command to store the server API credentials in configuration file

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni-tools#239]
To avoid passing the API credentials for every call, adding an `mgrctl connect` command testing the connection to the API server and storing the credentials in the config file would be cool.

**Comment by mmmmmmpc** [comment]
Very convenient for the user, indeed. 
It will make the behaviour similar to `kubectl`, something becoming a well known control tool.

**Comment by aaannz** [comment]
PRs merged, all done here
