### ISSUE TITLE
Create a SQL sub-command

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#245]
We would need an SQL sub-command to allow users to run SQL commands the same way we have the spacewalk-sql. Several times, in the context of L3 issues, we need to send SQL statements the customers need to run on the server.
We want to avoid the need to copy files or enter in the terminal to run this command.

Implementation can be just a wrapper for the existing spacewalk-sql command that exists inside the server container.

We can put it as a sub-command of support.

**Comment by rjmateus** [comment]
ping @admd and @cbosdo for awareness

**Comment by cbosdo** [comment]
BTW I already use this from my laptop to get SQL commands on a remote server:
```
export CONTAINER_CONNECTION=dev
mgrctl exec -ti -- spacewalk-sql -i
```
