### ISSUE TITLE
Allow tuning proxy httpd and squid configurations

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#263]
User may need to tune some parameters on the proxy squid and apache https containers. We would like to avoid adding another volume or ask users to enter container's terminal and change/add any new file.
The goal is to have a mechanism that allow users to tune the parameters without need of extra volume.

We will rely on mounting a file in pre-defined location.

# Install

## Podman
For podman  when users are installing the proxy services using mgrpxy, they would pass the path for the tuning file for apache and squid. The tuning file needs to be created before deploying.
mgrpxy will generate the systems unit file mounting the files.

**apache**: Place the file at: `/etc/apache2/conf.d/tuning.conf`. It will automatically be included by apache.
**squid**: Place the file at: `/etc/squid/squid_tuning.conf`. At container start, we can enhance the config script to append a "include" of the file in the squid configuration file (we are already manipulating it).

## Kubernetes

Have a configuration map, that will be materialized in the same pre-defined locations we have for podman. All automation done with proxy helmchart and mgrpxy.

# Migrate

We can improve the migrate command to also receive the tunning files and just update those tunning configurations.

**Comment by rjmateus** [comment]
relates to: https://github.com/SUSE/spacewalk/issues/20642

**Comment by cbosdo** [comment]
We also need to allow setting up HSTS on the Proxy's apache

**Comment by mbussolotto** [comment]
changes ready to be reviewed ^^^. The flags are available for `install` and `upgrade`, so it would be possible to change an existing environment without tuning by passing the flags to an `upgrade` command.

**Comment by mbussolotto** [comment]
PR merged
