### ISSUE TITLE
mgrpxy install podman: Add more "podman-mount-*" options

### ISSUE THREAD

**Issue by jmozd** [uyuni-project/uyuni-tools#265]
WFE ("wish for envancement", rather than RFE :D )

For podman environments, mgrpxy offers options to mount local directories for *some* of the "volumes" instead of having these created as default volumes by podman. 

I'd like to see the options list extended to i.e. the tftpboot mount: In some very special situations, local solutions were created to sync the tftpboot files from Cobbler / Uyuni Server to the Uyuni Proxies by very other mechanisms than "tftpsync". These mechanisms would be hard to integrate into the Proxy pod, therefore specifying the host-based directory (i.e. /srv/tftpboot ;) ) would be welcome.

**Comment by mbussolotto** [comment]
since option `podman-mount-*` already exists for `mgradm` it shouldn't be complicated to add it also for `mgrpxy`. Not sure besides `tftpboot` which may be the folder.
@rjmateus @cbosdo

**Comment by rjmateus** [comment]
I would say we can create the mechanism, and add just this folder. If needed it can be extended to add others

**Comment by jmozd** [comment]
We only later on noticed that there'S a tftp *proxy* in the container, pulling the files via HTTP. So there's nothing gained from creating a separate local mount point... I'm closing this issue, my "WFE" isn't applicable.
