### ISSUE TITLE
Merge multiple configuration files

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni-tools#271]
Add configuration file path in `/etc/uyuni/uyuni-tool.yaml` and merge all configuration files we find. This would be needed for cloud version to define default images locations.

**Comment by aaannz** [comment]
Discussion wrt. opensuse https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/KWRBTAVQ6MGHVAHKDZZ6GIRX4RMHKHQ6/#K2TECQS67ECKZD5GDD3JMBHPNCGYTT7S
