### ISSUE TITLE
HUB: allow mounting a folder for export/import

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#312]
Our existing customers are using HUB ISSv2 to export content to a folder normally mounted as NFS on the hub server and peripheral.
We need a way to allow mounting this folder on the containerized server.
User should be able to mount the NFS anywhere on the host OS and then mount it on the containerized server.

One option is to use the user parameters and provide some extra podman variable where user can define an extra mounting point.

See: https://github.com/uyuni-project/uyuni-tools/issues/311

**Comment by mbussolotto** [comment]
do we want it just for hub? I was thinking a command like 
```
mgradm hub mount $FOLDER
```
where the $FOLDER in host system is mounted in the same path inside container

**Comment by rjmateus** [comment]
upvote for your proposal Michele
