### ISSUE TITLE
Remove flags from install command on podam to define the storage location

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#313]
It will be replace with: https://github.com/SUSE/spacewalk/issues/24358

**Comment by cbosdo** [comment]
This could affect QE as I think they use those. @nodeg do you know that?

**Comment by nodeg** [comment]
About what flags are we exactly talking? And for what tool? Both `mgradm` and `mgrpxy`?

**Comment by cbosdo** [comment]
> About what flags are we exactly talking? And for what tool? Both `mgradm` and `mgrpxy`?

```
      --podman-mount-cache string        Path to custom /var/cache volume
      --podman-mount-postgresql string   Path to custom /var/lib/pgsql volume
      --podman-mount-spacewalk string    Path to custom /var/spacewalk volume
      --podman-mount-www string          Path to custom /srv/www/ volume
```

**Comment by nodeg** [comment]
Thank you. AFAICS, we do not use those flags in the test suite in Uyuni or in sumaform.
