### ISSUE TITLE
Add `--purge-images` parameter to uninstall commands

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni-tools#317]
As of today, the uninstall doesn't touch the images. Adding a flag to remove them would be nice.
To also make the configuration nicer the `--purgeVolumes` flag should be renamed in `--purge-volumes` so that the configuration for them could be something like:

```
purge:
  volumes: true
  images: true
```

**Comment by mbussolotto** [comment]
adding this commit for reference since I struggle to understand why flags with dash were ignored https://github.com/uyuni-project/uyuni-tools/pull/320/commits/1e07d0ed5484cb02cb706a94237abcbdbe48ab2f
