### ISSUE TITLE
Command "mgradm support config" should save the support file with a date to avoid collisions

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#318]
The support config command should save the file and avoid collisions with other older support configs instead of overwrite. To archive this we can add the date to the export file.

File name should follow the same name structure as before: `SCC_<HOSTNAME>_DATE.txz`
example: `scc_stfpospap10_240412_1217.txz`

After extracting, the compress file, all files need to be located in a subdirectory with the same name as the file (without the extension). Currently it's extracting files that can lead to conflict if more the one support config is extracted in one folder.

**Comment by admd** [comment]
@rjmateus I am moving this issue under GMC here https://github.com/SUSE/spacewalk/issues/24298 for now. It would be good if we can fix it for GMC. We still have a week for branch freeze.

**Comment by admd** [comment]
PR has been merged. Feel free to close the issue.
