### ISSUE TITLE
upgrade command use variables name migrate

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#319]
We have a migrate command to migrate from suse manager 4.3 where we can define from where to read the migrate image from.

On the upgrade command, we can also define the image to be used for a major upgrade, especially when we need a database upgrade. This will only be needed for an upgrade between major versions, like 5.0 to 5.1.

Currently, this command uses "migrate" variable names and in the help inforamtion. We would need to change that and adapt to reference "upgrade" name instead and avoid any confusion.

At this stage, should we instead of rename just hide/remove these variables? They will only be needed one year from now, and until there can cause confusion.

print for reference:

![image](https://github.com/uyuni-project/uyuni-tools/assets/2996004/4d3f1dcf-2618-4c4c-866d-fd5258ea0ce2)

**Comment by cbosdo** [comment]
both functions share the code... it should be rather quick to change. but worth case yes those could be hidden
