### ISSUE TITLE
Bug 1226191 - Missing architecture in the buildtag of helm charts

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni-tools#358]
```
--helm-proxy-chart string       URL to the proxy helm chart (default "oci://registry.suse.de/devel/galaxy/manager/head/containerfile/suse/manager/5.0/x86_64/proxy-helm")
```
instead it should be 
```
oci://registry.suse.de/devel/galaxy/manager/head/charts/suse/manager/5.0/proxy-helm
```
so `s/containerfile/charts` and `ARCH` is missing

**Comment by deneb-alpha** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1226191

**Comment by cbosdo** [comment]
As a recap, the uyuni-tools PR is needed with the current setup and requires prjconf adjustments for HEAD, no other project. The Uyuni PR may be closed if we keep the helm charts where they currently are, without any architecture in the name (which is the most sensible thing to do).
