### ISSUE TITLE
node-exporter port 9100 conflicts with traefik

### ISSUE THREAD

**Issue by nadvornik** [uyuni-project/uyuni-tools#362]
Uyuni container use port 9100 for node exporter. The same port  is used by traefik default configuration to exports it's own metrics, so there is a conflict and traefik fails to start:

```
2024/06/13 09:02:29 traefik.go:80: command traefik error: error while building entryPoint node-exporter: error preparing server: error opening listener: listen tcp :9100: bind: address already in use
```
The failure can be hidden because kubernetes keeps running the traefik with the old configuration. 

https://github.com/uyuni-project/uyuni-tools/pull/215
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L704

@cbosdo @witekest

**Comment by witekest** [comment]
Do we need _node exporter_ in Kubernetes deployments? It provides hardware metrics of the underlying node so I think it's out of scope for SUMA server monitoring.
It should be safe to remove _node exporter_ from the image for Kubernetes deployments, disable the service or remove the port mapping.
For container metrics we could switch to cAdvisor.

**Comment by rjmateus** [comment]
For now, disable the port export for kubernetes. Next step is to try cAdvisor and decide what and how we should support. cAdvisor is part of packHUB only, we may need to support it on our side.
