### ISSUE TITLE
mgradm upgrade podman list doesn't should tags or error when not authenticated

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/uyuni-tools#372]
When we run the command `mgradm upgrade podman list` without being authenticated we don't get any tags and it finishes with success.
We should try to provide some insides in case the registry needs authentication to return the tags.
![image](https://github.com/uyuni-project/uyuni-tools/assets/2996004/4ccd51e4-e4db-42bf-a438-d689164e9035)

**Comment by mbussolotto** [comment]
it should be an easy fix, this part of code should be added in list function https://github.com/uyuni-project/uyuni-tools/blob/311105e2754979f2e7035fd8883f0e48631921b0/mgradm/shared/podman/podman.go#L344-L351

**Comment by mbussolotto** [comment]
I'll verify it on top of https://github.com/uyuni-project/uyuni-tools/pull/400, I think now just

`authFile, cleaner, err := shared_podman.PodmanLogin()`

would be enough
