### ISSUE TITLE
mgradm migrate podman tries to migrate to newest version even when legacy install is not.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni-tools#423]
When trying to migrate from legacy to a podman version of uyuni the migration pulls the newest image of uyuni not the version used by the legacy server. 
Legacy server is 2024.05 .
Is this as intended?
The migration failed.
Comparing logs it has stopped right before migrating postgresql from 14 to 16.
Last lines in the migration:
```
Altering configuration for domain resolution...
Altering configuration for container environment...
DONE
```
```
mgradm -v
mgradm version 0.1.17 (Master 311105e)
```

**Comment by rjmateus** [comment]
It should be able to migrate to the latest version. By default mgradm migrate and install uses the latest tag to download the image.
Do you have any error in the logs or in the command line?

**Comment by j-kihet** [comment]
Tryed again and it worked this time.
