### ISSUE TITLE
install and uninstall cert-manager labels

### ISSUE THREAD

**Issue by rjpmestre** [uyuni-project/uyuni-tools#436]
While working on [this ticket](https://github.com/uyuni-project/uyuni-tools/issues/375), we noticed labels were not behaving/being applied as we intended.
In this specific case: linstalledby=mgradm

This ticket is meant to remember about reasoning behind this requirement and where and how it should be applied.

_Originally posted by @cbosdo in https://github.com/uyuni-project/uyuni-tools/pull/420#discussion_r1708875284_

**Comment by cbosdo** [comment]
Fixing it with my current refactoring for kubernetes.
