### ISSUE TITLE
bash-completion issue

### ISSUE THREAD

**Issue by kcote-ncar** [uyuni-project/uyuni-tools#438]
Hello,

After upgrading the mgradm and mgrctl rpm packages I am getting the following error message when issuing a single tab and the message is repeated after the second tab and then shows the subcommand results:
```bash
mgradm -bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found
-bash: __mgradm_debug: command not found

distribution  help          inspect       migrate       scale         status        support       upgrade       
gpg           hub           install       restart       start         stop          uninstall
```
```bash
mgrctl -bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found

api   cp    exec  help  term
```
The uyuni-tools are installed on AlmaLinux 9 servers from the uyuni-tools [repository](https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/EL_9/) for EL9 systems.

Installed versions:
```bash
mgradm-0.1.21-1.4.uyuni.x86_64
mgrctl-0.1.21-1.4.uyuni.x86_64
mgrctl-bash-completion-0.1.21-1.4.uyuni.noarch
mgradm-bash-completion-0.1.21-1.4.uyuni.noarch
```
Uyuni Server doesn't need to be deployed to recreate the issue. The uyuni-tools have been installed on two separate servers. One server has Uyuni Sever deployed and running and the other server only has the tools installed. Both systems are exhibiting the same debug message after upgrading the rpms.

Let me know if you need additional information.

**Comment by mbussolotto** [comment]
Thanks for reporting. It will be fixed by this PR https://github.com/uyuni-project/uyuni-tools/pull/417 (in particular by this commit https://github.com/uyuni-project/uyuni-tools/pull/417/commits/0fbabe804fb24aca520d4c60c252cbadc49ccdcf )

**Comment by kcote-ncar** [comment]
I think this issue isn't fully resolved. mgradm is functioning properly with bash completion but mgrctl is still exhibiting this issue.

```bash
mgrctl -v
mgrctl version 5.1.1 (Master c6dad0e)
```

With double tab this is the output of mgrctl:
```
mgrctl -bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
-bash: __mgrctl_debug: command not found
```
Can this issue be reopened or would you like a new issue submitted?

Thanks!

**Comment by ppanon2022** [comment]
mgrpxy also seems to have this issue.

**Comment by deneb-alpha** [comment]
@ppanon2022 the PR that fixes also mgrpxy is the same that fixes mgrctl: https://github.com/uyuni-project/uyuni-tools/pull/481
the next Uyuni release will deliver this fix.

Thanks to both @kcote-ncar and @ppanon2022 for reporting.
