### ISSUE TITLE
Add proxy install command

### ISSUE THREAD

**Issue by tanganellilore** [uyuni-project/uyuni-tools#62]
Hi team,

as per https://github.com/uyuni-project/uyuni/issues/7589 I will opend this issue to track here the add of proxy command install on uyuniadm.

Let me know if I can submit something that can address this feature.

Thanks

**Comment by cbosdo** [comment]
Thanks for the issue. We first need to figure out how we want to get the proxy-related commands like this one in the tools / subcommands. @admd @rjmateus  any idea?

**Comment by rjmateus** [comment]
On this I see two options: the verb and then the component or the other way around:
- "uyuniadm server/proxy install/migrate/.."
- "uyuniadm install/migrate/.. server/proxy"

When writing it looks more intuitive to have the component and then the verb. I would also make clear which actions are available for each component (and have some component-specific commands).

What do you guys think? Any feeling on what would look better?

**Comment by tanganellilore** [comment]
I don't know if it was addressed the question to me, anyway  if we compare to kubectl or other cli tools (like git) they choice to use before the verb and then the Component.
In other cli, like awx, where tou need to have a real componente they use Component then verb. 

In my opinion is better the first option for this use case, is more intuitive and flexible.

**Comment by cbosdo** [comment]
Implemented by https://github.com/uyuni-project/uyuni-tools/pull/96 . I forgot to update the issue here
