### ISSUE TITLE
Enhance version command

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni-tools#75]
Add useful data to the version command like the go version, a commit hash or build tags.
It could also be useful to provide YAML and/or JSON output for easy use by scripts.

**Comment by rjmateus** [comment]
This command is to be used by customers. Would be needed to provide the go version and commit hash? In which use case do you think it can be helpfull?

**Comment by cbosdo** [comment]
> This command is to be used by customers. Would be needed to provide the go version and commit hash? In which use case do you think it can be helpfull?

This could be useful to make sure we have the version built from our packages
