### ISSUE TITLE
Installation fails after an uninstallation

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni-tools#89]
Once I uninstall, and I try to install again, I receive this error, as if something has not be fully removed
```
4:22PM FTL /etc/systemd/system/uyuni-server.service file already present, not overwriting
```

**Comment by cbosdo** [comment]
@mbussolotto was the installation you are removing successful or did it fail? That kind of behavior could happen if the service file was installed but the container isn't running

**Comment by mbussolotto** [comment]
I can't remember, let's keep the issue opens so I remember to re-check it next time

**Comment by mbussolotto** [comment]
fixed
